name: forkit CI
on: [push]
jobs:
  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forkit repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install tsc
      - run: npx tsc


  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forkit repo
        uses: actions/checkout@v3
      - id: setup
        name: Setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun test

